/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./templates/**/*.html",
    "./shared/**/*.js",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#27d5f0",
        "on-secondary-container": "#c4abff",
        "primary-fixed-dim": "#3cd7ff",
        "on-tertiary-container": "#005865",
        "surface-container-highest": "#323539",
        "surface-container-low": "#191c1f",
        "tertiary-fixed-dim": "#2fd9f4",
        "secondary-container": "#571bc1",
        "tertiary-fixed": "#a2eeff",
        "on-secondary": "#3c0091",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#5516be",
        "on-tertiary-fixed": "#001f25",
        "on-error": "#690005",
        "inverse-primary": "#00677e",
        "inverse-surface": "#e1e2e7",
        "secondary-fixed": "#e9ddff",
        "surface-variant": "#323539",
        "on-surface-variant": "#bbc9cf",
        "on-background": "#e1e2e7",
        "surface-container": "#1d2023",
        "on-secondary-fixed": "#23005c",
        "secondary": "#d0bcff",
        "tertiary": "#93ecff",
        "surface-container-lowest": "#0c0e12",
        "on-primary": "#003642",
        "outline-variant": "#3c494e",
        "error": "#ffb4ab",
        "primary-fixed": "#b4ebff",
        "surface": "#111417",
        "secondary-fixed-dim": "#d0bcff",
        "on-tertiary-fixed-variant": "#004e5a",
        "background": "#111417",
        "on-primary-fixed": "#001f27",
        "on-primary-container": "#00586b",
        "inverse-on-surface": "#2e3134",
        "on-tertiary": "#00363e",
        "surface-container-high": "#282a2e",
        "primary": "#a8e8ff",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#004e5f",
        "on-surface": "#e1e2e7",
        "surface-tint": "#3cd7ff",
        "surface-dim": "#111417",
        "primary-container": "#00d4ff",
        "outline": "#859398",
        "surface-bright": "#37393d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "container-max": "1440px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "label-caps": ["Space Grotesk"],
        "metric-xl": ["IBM Plex Sans"],
        "display-lg-mobile": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "metric-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "500" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
